### ISSUE TITLE
request_wrapper.py

### ISSUE THREAD

**Issue by shane-breeze** [cms-sw/xsecdb#6]
Is there any way to use `request_wrapper.py`, found [here](https://github.com/cms-sw/xsecdb/tree/39e02a81e6708e7c11b8942bae453aaf13c56353/scripts/wrapper), outside of CERN's lxplus. My current issue is when it runs the `getCookie.sh` script which works fine on lxplus but nowhere else since it cannot find `cern-get-sso-cookie`.

**Comment by szaleski** [comment]
As of right now, only use within lxplus is supported. please use lxplus for XSDB for the time being.
